refactoring and add proxy arg
testit-tms/autotest-integration-python pull request #11
Opened 2021-06-20 15:44 UTC by dc-avasilev

close:
https://github.com/testit-tms/autotest-integration-python/issues/10
https://github.com/testit-tms/autotest-integration-python/issues/2

2021-06-21 17:01 UTC, testit-tms requested changes

2021-06-22 07:59 UTC, dc-avasilev commented on testit_pytest/src/listener.py
> +            if hasattr(item.function, 'test_externalID') and item.own_markers:
this is your old code, I did not change the logic, I just optimized it visually for easier perception, what do you want me to do here? I can return everything as it was with you =)

2021-06-22 08:15 UTC, dc-avasilev commented on testit_pytest/src/listener.py
> +            if hasattr(item.function, 'test_externalID') and item.own_markers:
oops sorry I saw that the indentation moved out and that the condition levels changed

2021-06-22 08:27 UTC, dc-avasilev commented on testit_pytest/src/listener.py
> +            if hasattr(item.function, 'test_externalID') and item.own_markers:
++
repaired

2021-06-22 08:27 UTC, dc-avasilev commented on testit_pytest/src/plugin.py
> +    parser.getgroup('debug').addoption(
++
repaired

2021-06-22 08:30 UTC, dc-avasilev commented on README.rst
> +    pytest --testit --testrunid=${TEST_RUN_ID} --url=${URL} --privatetoken=${PRIVATE_TOKEN} --testit_proxy='{"http":"http://localhost:8888","https":"http://localhost:8888"}'
++
repaired

2021-06-25 17:28 UTC, merged