Add testrun_name at config
testit-tms/autotest-integration-python pull request #19
Opened 2021-08-03 18:27 UTC by PavlovForGithub

2021-08-13 13:19 UTC, testit-tms requested changes

2021-08-13 13:19 UTC, testit-tms commented on testit_pytest/src/listener.py
> +        elif hasattr(self, 'testrun_name'):
Вместо дополнительного elif лучше добавить в строку названия тест-рана тернарный if:
`f'{self.testrun_name if hasattr(self, "testrun_name") else "LocalRun"} {datetime.today().strftime("%d %b %Y %H:%M:%S")}'`

2021-08-13 13:34 UTC, dc-avasilev commented on testit_pytest/src/listener.py
> +        elif hasattr(self, 'testrun_name'):
так-же не помешало бы это добавить в качестве аргумента cli в [файле](https://github.com/testit-tms/autotest-integration-python/blob/main/testit_pytest/src/plugin.py)

2021-11-24 04:32 UTC, testit-tms commented
Функционал добавлен в версии testit-pytest 0.2.10

2021-11-24 04:32 UTC, closed without merging